name: shared_preferences
publish_to: none
description: Flutter plugin for reading and writing simple key-value pairs.
  Wraps NSUserDefaults on iOS and SharedPreferences on Android.
repository: https://github.com/flutter/packages/tree/main/packages/shared_preferences/shared_preferences
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+shared_preferences%22
version: 2.3.2

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: shared_preferences_android
      ios:
        default_package: shared_preferences_foundation
      linux:
        default_package: shared_preferences_linux
      macos:
        default_package: shared_preferences_foundation
      web:
        default_package: shared_preferences_web
      windows:
        default_package: shared_preferences_windows

dependencies:
  flutter:
    sdk: flutter
  shared_preferences_android:
    git: https://github.com/kumsumit/shared_preferences_android.git
  shared_preferences_foundation: 
    git: https://github.com/kumsumit/shared_preferences_foundation.git
  shared_preferences_linux: 
    git: https://github.com/kumsumit/shared_preferences_linux.git
  shared_preferences_platform_interface: 
    git: https://github.com/kumsumit/shared_preferences_platform_interface.git
  shared_preferences_web: 
    git: https://github.com/kumsumit/shared_preferences_web.git
  shared_preferences_windows: 
    git: https://github.com/kumsumit/shared_preferences_windows.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

topics:
  - persistence
  - shared-preferences
  - storage
